### ISSUE TITLE
autobind-decorator throws error

### ISSUE THREAD

**Issue by Jinnified** [ufocoder/redux-universal-boilerplate#10]
Hi

I was trying to use this autobind lib which auto bind this to react custom methods, however, the server will throw error during compilation.
https://github.com/andreypopp/autobind-decorator

`und/redux-universal-boilerplate/dist/server.js:857
        proto[key] = storedPrototype[key];
                   ^
TypeError: Cannot set property titleClickHandler of #<Test> which has only a getter...
`

**Comment by ufocoder** [comment]
This issue is not concerned with current boilerplate.
Your `autobind-decorator` issue have already opened there https://github.com/andreypopp/autobind-decorator/issues/32, check it please there
