### ISSUE TITLE
how add styles file for <body>?

### ISSUE THREAD

**Issue by dokenzy** [ufocoder/redux-universal-boilerplate#14]
I am going to add style for <body> with stylus syntax, exactly entire template.

I have created new stylus file in src/server/containers/Html/assets/foo.styl and added `import './assets/styles.styl';` in src/server/containers/Html/index.js, edited `<body>` to `<body className="blahblah">`.

Rendered HTML is good: <body class="blahblah"> but not applied css.

I don't know how to add foo.styl for the index.js file.

Could you show me some code for this?

Thanks.

**Comment by ufocoder** [comment]
@dokenzy tag `<body>` is rendered by server bundle and I recommend you to add css classes to your root container of application (it will be `common` code) and locate styles near of this container also.

**Comment by dokenzy** [comment]
In my case, `<body className="blahblah">` doesn't make any error but I'm following your suggestion.
It is coming along nicely.
Thanks
