### ISSUE TITLE
404 on /assets/client.js with npm run watch

### ISSUE THREAD

**Issue by williamoliveira** [ufocoder/redux-universal-boilerplate#19]
Steps I followed:

`git clone https://github.com/ufocoder/redux-universal-boilerplate.git myapp`
`cd myapp`
`npm install`
`npm run watch`

`wget http://localhost:8000/assets/client.js` // ERROR 404: Not Found.

No code was touched.
Maybe some dependence update broke it?

**Comment by williamoliveira** [comment]
Just saw this issue was already filled at #8, but his strange solution didn't worked for me

**Comment by ufocoder** [comment]
@williamoliveira Process for building client and server bundles are asynchronous. You should run `wget` after you will get in console:

```
[2] Express server listening on port 8000
```
