### ISSUE TITLE
Client-side runtime error "ReferenceError: regeneratorRuntime is not defined"

### ISSUE THREAD

**Issue by williamku** [ufocoder/redux-universal-boilerplate#21]
I downloaded your latest boilerplate and found that, after initial page loads, clicking on the 2nd tab will generate runtime error in the browser console:  "ReferenceError: regeneratorRuntime is not defined"
   
after some research, I found that adding a line as follows will resolve it:

file:   webpack/client/config.js

line number:  82

before adding the line:
   entry: [
      path.resolve(path.join(appPath, 'src', 'client')),
  ]

after adding the line:
   entry: [
      'babel-polyfill',
      path.resolve(path.join(appPath, 'src', 'client')),
  ]

**Comment by ufocoder** [comment]
@williamku I've updated packages, update boilerplate please. Also note that boilerplate need `"node": ">=6.9.0"`
