### ISSUE TITLE
Watch mode have no styles. And just doesn't work properly

### ISSUE THREAD

**Issue by RIP21** [ufocoder/redux-universal-boilerplate#22]
I run `build` first.
Then I run `watch`. 
But it has `clean` in its script, so it's remove everything from static.
So Hot reload is not working, `client.js` is 404 on opened page.
Removing clean, keeps styles, but changes do not appear on the page until rerun of `watch`. And then it's blinking, and before styles etc apply it has changes that we made before this rerun and then they disappear after, probably, client.js is starting its work.
I'm working on the complete clean clone of this repository without any changes.
Also, store in the `server.js` in the hot.module replacement part is undefined since instantiated in the scope of `app.use{}`

Don't get me wrong :) Whole boilerplate looks nice, but these problems can't give me a chance to start using it.

Also I'm using Windows if it makes any sense.
And yeah, after Ctrl+C оne process is alive taking port, so I need to kill it manually all the time T_T

**Comment by ufocoder** [comment]
@RIP21 Thanks for issue.

1) Blinking in `watch` mode it's a normal behaviour, because in `watch` mode styles are loaded though `style-loader` that add styles in the head of document. When you `build` bundle styles will be  extracted into separated files by `extract-text-webpack-plugin` and there will not be blinking

2) I try to investigate `store` problem and resolve it this weekends 

3) I can't promise to resolve this issue nearest time because I have `mac os` :)

**Comment by ufocoder** [comment]
@RIP21 I've fixed reducers updating by commit 8a9a773b80d5c5096fc3cfc6c538cba42d5f7a69. Please check it

**Comment by RIP21** [comment]
@ufocoder about blinking, I know that :)  Webpack extract text later will extract CSS to separate file so it will no longer blink, but the problem is that watch didn't work properly and that it's cleaning up assets etc.

**Comment by ufocoder** [comment]
@RIP21 When you run `watch` webpack up `dev-server` where your static files will be hosted. This command run `watching` bundle for client side and server side and these operations are not synchonized, for example:

```
[1] > redux-universal-boilerplate@0.1.0 watch:server /Users/ufocoder/www/redux-universal-boilerplate
[1] > webpack --config webpack/server/watch.js
[1] 
[0] 
[0] > redux-universal-boilerplate@0.1.0 watch:client /Users/ufocoder/www/redux-universal-boilerplate
[0] > webpack-dev-server --config webpack/client/watch.js
```

You have to wait a bit when all will be hosted
