### ISSUE TITLE
react-router-dom

### ISSUE THREAD

**Issue by fanny** [ufocoder/redux-universal-boilerplate#29]
I noticed that you used the react-dom in the project, but since it is a web project, it is best to use the react-router-dom, which provides specific components for web development and re-exports all the functions of the react-router. 
You can check this on a issue with the react-router's own design: https://github.com/ReactTraining/react-router/issues/4648

**Comment by ufocoder** [comment]
@FannyVieira Could you help to improve this within hacktoberfest? :)

**Comment by fanny** [comment]
of course I'll try
