### ISSUE TITLE
Stopping and restarting npm run watch does not correctly kill the proxy server

### ISSUE THREAD

**Issue by granttaylor91** [ufocoder/redux-universal-boilerplate#3]
Hi,

First of all, thank you so much for making this. It's fantastic.

I'm encountering the following issue with regards to this scenario:

I use npm run watch, when a change is made that is not handled by hot-reloading and a server restart is required. Terminating the batch task appears to only terminate the webpack dev server and not the proxy server at localhost:8000, despite the --kill-others flag being set. When re-running the npm run watch command, an error stating that the address (localhost:8000) is already in use is thrown when the start command is eventually reached. 

Please let me know if I can explain or help any further, I am quite new to concurrently and webpack so this one is puzzling me right now.

**Comment by ufocoder** [comment]
@granttaylor91 Could you write your version of NodeJS and OS type?

**Comment by granttaylor91** [comment]
@ufocoder Sorry, I should have mentioned that...

I'm on Node v6.1.0 and npm 3.8.6
Windows 10, running scripts via cmd

**Comment by ufocoder** [comment]
@granttaylor91 Package `concurrently` is used in this boilerplate. There's an issue for Windows https://github.com/kimmobrunfeldt/concurrently/pull/21

**Comment by ufocoder** [comment]
@granttaylor91 Switch to [this branch](https://github.com/ufocoder/redux-universal-boilerplate/tree/3_npm-run-all) and try to run `watch` command on your Windows system.

**Comment by kimmobrunfeldt** [comment]
These issues should be now fixed in 3.0.0-rc1. `npm i -g concurrently@3.0.0-rc1`. Please open a new issue to concurrently repo if this is not the case. I'll release the 3.0.0 soonish.

**Comment by ufocoder** [comment]
@kimmobrunfeldt it helps. thx

**Comment by kimmobrunfeldt** [comment]
Now I would recommend using 3.1.0 version as it contains some important bug fixes for Windows.

**Comment by ufocoder** [comment]
@kimmobrunfeldt Thanks for care, I have used already the 3.1.0 version https://github.com/ufocoder/redux-universal-boilerplate/commit/da732ba1d714aff85e2bfee873d29539fa136332#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R85

**Comment by kimmobrunfeldt** [comment]
Alrighty, awsome!
