### ISSUE TITLE
Acceptance tests

### ISSUE THREAD

**Issue by ufocoder** [ufocoder/redux-universal-boilerplate#31]
Need to implement several acceptance tests and add task for `travis-ci`. 

For testing could be used [webdriver.io](http://webdriver.io/)

**Comment by anishkny** [comment]
How about using [GoogleChrome/puppeteer](https://github.com/GoogleChrome/puppeteer) and [ava](https://github.com/avajs/ava)? I can work something out soonish. LMK.

Something along the lines of: https://github.com/anishkny/realworld-e2e-test

**Comment by ufocoder** [comment]
@anishkny `Puppeteer` is a great tool you could add it to this boilerplate

And about task runner. Boilerplate has already task runner such as `mocha`

**Comment by anishkny** [comment]
Sounds good. Will try to have something working!
