### ISSUE TITLE
enable stylus

### ISSUE THREAD

**Issue by Jinnified** [ufocoder/redux-universal-boilerplate#6]
Hi

I was trying to add stylus, the stylus-loader as the webpack loader only works on client side, so i was trying to update the webpack/client/config.js, by adding the loaders such as:

`loaders: [
    { test: /\.styl$/, loader: 'style-loader!css-loader!stylus-loader' }
  ]`

however the app still throws an error: ERROR in ../src/common/components/Layout/layout.styl
Module parse failed

and it's still complaint about i do not have the right loader for .styl files. Just wondering if i am adding it at the right place?

thanks

**Comment by ufocoder** [comment]
@Jinnified I've just added support of stylus for boilerplate, please check it

**Comment by Jinnified** [comment]
thanks man, that works, however, i;d like to add yeticss to it as well, it seems that by adding 

stylus: {
    use: [yeticss()]
  }

in the webpack client config.js doesn't take effect, and there is no error either, i wonder if i need to do something in the isompohic config too?

**Comment by Jinnified** [comment]
sorry my bad, forgot to add @import 'yeticss' in my styl file
